- .github/dependabot.yaml
- .github/workflows/ci.yaml
**Summary**
This provides the start of the automated actions run when contributors submit a pull request and on a merge to main branch
It checks any links within our files (HTTP, markdown, etc)
add link checker
**Other info**
closes #10
> add link checker action

- .lycheeignore
- CONTRIBUTING.md
- draft/01-audience.md
**Summary**
Migrate revised content from the DevGuide [introduction section](https://github.com/OWASP/DevGuide/blame/master/00-Introduction/Introduction.md), originally provided by @ frenchi and also from the discussion ['Audience for Developer Guide'](https://github.com/OWASP/www-project-developer-guide/discussions/6) #6 
revised content for audience section
**Other info**
> revised content for audience section

- _data/draft.yaml
- draft/00-toc.md
- draft/05-security-requirements/00-toc.md
- draft/05-security-requirements/01-security-requirements.md
- draft/05-security-requirements/toc.md
- draft/06-secure-design/00-toc.md
- draft/06-secure-design/01-secure-design.md
- draft/06-secure-design/toc.md
- draft/07-container-security/00-toc.md
- draft/07-container-security/01-container-security.md
- draft/07-container-security/toc.md
- draft/08-open-source-software/00-toc.md
- draft/08-open-source-software/01-open-source-software.md
- draft/08-open-source-software/toc.md
- draft/09-secure-environment/00-toc.md
- draft/09-secure-environment/01-secure-environment.md
- draft/09-secure-environment/toc.md
- draft/10-security-testing-validation/00-toc.md
- draft/10-security-testing-validation/01-security-testing-validation.md
- draft/10-security-testing-validation/toc.md
- draft/toc.md
**Summary**
Rearranges the document structure, the old Overviews are now Introductions, and an overview / abstract is placed before each major section
Add introduction and overviews
**Other info**
> Add introduction and overviews

- _data/draft.yaml
- draft/00-toc.md
- draft/04-foundations/00-toc.md
- draft/04-foundations/04-crypto-principles.md
- draft/04-foundations/toc.md
- draft/toc.md
**Summary**
adds 'Principles of Cryptography' section to the Foundations chapter
this is mainly terminology and is based on the section 03-build/0x11-Cryptography.md of the old Dev Guide
add section on principles of crypto
**Other info**
> add section on principles of cryptography

- _data/draft.yaml
- draft/00-toc.md
- draft/04-foundations/00-toc.md
- draft/04-foundations/01-foundations.md
- draft/04-foundations/02-sdlc.md
- draft/04-foundations/03-security-principles.md
- draft/04-foundations/toc.md
- draft/toc.md
**Summary**
This provides a new section 'Principles of Security' in 04-foundations/03-security-principles
add section on security principles
**Other info**
> add section on security principles

- draft/01-audience.md
- draft/05-security-requirements/03-threat-modeling.md
**Summary**
This adds the section on threat modeling 05-security-requirements/03-threat-modeling
add section on threat modeling
**Other info**
closes #32
> Add threat modeling section

- .github/workflows/housekeeping.yaml
provides a workflow triggered every day to do housekeeping chores
add daily housekeeping workflow
no issue associated with this
Thanks for submitting a pull request! Please make sure you follow our [code of conduct][coc]
[coc]: https://github.com/OWASP/www-project-developer-guide/blob/main/CODE_OF_CONDUCT.md
> Add daily housekeeping workflow

- .github/workflows/ci.yaml
- .github/workflows/housekeeping.yaml
This pull request increases the number of retries for the link checker, because we get occasional timeouts waiting for linddun.org
increase link-checker retries
> increase link-checker retries

- README.md
- index.md
This adds the DevGuide logo to the project index page and the read-me file
add logo to index and read-me
> add logo to index and read-me

- .gitignore
- .wordlist.txt
- draft/05-security-requirements/00-toc.md
- draft/06-secure-design/00-toc.md
- draft/07-container-security/00-toc.md
- draft/08-open-source-software/00-toc.md
- draft/09-secure-environment/00-toc.md
- draft/10-security-testing-validation/00-toc.md
- tab_contributing.md
This add a new tab, requesting contributions to the Developer Guide
add tab on contributing
> add tab on contributing

- .github/workflows/ci.yaml
updates markdown lint action to version 12.0.0
update markdown lint action
> Update markdown lint action

- .github/workflows/ci.yaml
- .github/workflows/housekeeping.yaml
some patches for the pipelines
patches for pipeline actions
> patches for pipeline actions

- .wordlist.txt
- draft/06-design/01-threat-modeling/01-threat-modeling.md
Less document centered
Clarify relationship between threat modeling activity and records
> Clarified relationship between activity and records in first section.

- README.md
corrections to README text
corrections to text
> add period

- .wordlist.txt
- _data/draft.yaml
- draft/02-toc.md
- draft/04-foundations/02-secure-development.md
- draft/05-requirements/00-toc.md
- draft/05-requirements/04-security-rat.md
- draft/05-requirements/toc.md
- draft/toc.md
This provides the content for the page on SecurityRAT
add page for SecurityRAT
Closes #120
> Add page for SecurityRAT

- draft/09-training-education/01-secure-coding-dojo.md
provides the content for 09-training-education/09-secure-coding-dojo
add content for secure coding dojo
> add content for secure coding dojo

- .github/workflows/ci.yaml
- .wordlist.txt
- _data/draft.yaml
- draft/02-toc.md
- draft/11-operation/00-toc.md
- draft/11-operation/01-modsecurity-crs.md
- draft/11-operation/02-coraza.md
- draft/11-operation/03-modsecurity.md
- draft/11-operation/toc.md
- draft/13-security-gap-analysis/02-blt.md
- draft/toc.md
provide content for Bug Logging Tool , CRS, Coraza and ModSecurity
Closes #144 and closes #143
> provide content for Bug Logging Tool and Operations

- draft/13-security-gap-analysis/02-blt.md
Thanks for featuring us!
updating title
> Update title to OWASP Bug Logging Tool (BLT) on 02-blt.md

- .github/workflows/release.yaml
- _includes/banner.html
ensure release pipeline works OK
fix up sed commands for release pipeline
> fix up sed commands for release pipeline

- .wordlist.txt
- README.md
- draft/03-introduction.md
- draft/04-foundations/01-security-fundamentals.md
- draft/04-foundations/02-secure-development.md
- draft/04-foundations/03-security-principles.md
- draft/04-foundations/04-crypto-principles.md
- draft/04-foundations/05-top-ten.md
- index.md
Proof reading of the Foundations section
various improvements to Foundations sections
> Various improvements to Foundations

- .github/workflows/release.yaml
- draft/11-operation/01-modsecurity-crs.md
- release/11-operation/01-modsecurity-crs.md
There is a bug in the release workflow that stops it running
format the pull-request title
> Fix for the release workflow

- .github/workflows/release.yaml
bug fix for release workflow
bug fix for release workflow
> bug fix for release workflow

- .github/workflows/ci.yaml
- .github/workflows/housekeeping.yaml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- draft/04-foundations/05-top-ten.md
- draft/12-metrics/00-toc.md
- draft/12-metrics/toc.md
updates version used to Ubuntu LTS 24.04 
update versions used in workflow steps
> update versions used in workflows

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- .lycheeignore
- contributing.md
- draft/03-introduction.md
- index.md
Various chores to update the development guide to version 4.1.1
* add reference to media kit, closes #215 
various minor updates across the guide
> Various minor updates across the guide

- draft/03-introduction.md
- draft/04-foundations/toc.md
- draft/05-requirements/toc.md
- draft/06-design/01-threat-modeling/03-threat-dragon.md
- draft/06-design/01-threat-modeling/toc.md
- draft/06-design/02-web-app-checklist/toc.md
- draft/06-design/toc.md
- draft/07-implementation/01-documentation/03-cheatsheets.md
- draft/07-implementation/01-documentation/toc.md
- draft/07-implementation/02-dependencies/toc.md
- draft/07-implementation/03-secure-libraries/toc.md
- draft/07-implementation/04-dos-donts/toc.md
- draft/07-implementation/toc.md
- draft/08-verification/01-guides/toc.md
- draft/08-verification/02-tools/toc.md
- draft/08-verification/03-frameworks/toc.md
- draft/08-verification/04-vulnerability-management/toc.md
- draft/08-verification/05-dos-donts/toc.md
- draft/08-verification/toc.md
- draft/09-training-education/01-vulnerable-apps/toc.md
- draft/09-training-education/toc.md
- draft/10-culture-process/02-security-champions/toc.md
- draft/10-culture-process/toc.md
- draft/11-operations/toc.md
- draft/13-security-gap-analysis/01-guides/toc.md
- draft/13-security-gap-analysis/toc.md
fix paths to logos
fix paths to logos
> fix paths to logos

- draft/14-appendices/01-implementation-dos-donts/Session Management
> Update Session Management

- _data/draft.yaml
- draft/06-design/01-threat-modeling/04-cornucopia.md
- draft/06-design/02-web-app-checklist/01-define-security-requirements.md
- draft/06-design/02-web-app-checklist/02-frameworks-libraries.md
- draft/06-design/02-web-app-checklist/03-secure-database-access.md
- draft/06-design/02-web-app-checklist/04-encode-escape-data.md
- draft/06-design/02-web-app-checklist/05-validate-inputs.md
- draft/06-design/02-web-app-checklist/06-digital-identity.md
- draft/06-design/02-web-app-checklist/07-access-controls.md
- draft/06-design/02-web-app-checklist/08-protect-data.md
- draft/06-design/02-web-app-checklist/09-logging-monitoring.md
- draft/06-design/02-web-app-checklist/10-handle-errors-exceptions.md
It would be good to link across to the cornucopia cards from the checklist
The first step to cross referencing to cornucopia is provide identifiers to the checklist
then the checklists can link across to the cornucopia cards
provide identifiers to the checklist
> provide identifiers to the checklist

- .github/workflows/ci.yaml
- .wordlist.txt
- _data/draft.yaml
- _data/release.yaml
- draft/02-toc.md
- draft/11-operations/00-toc.md
- draft/11-operations/04-crs.md
- draft/11-operations/toc.md
- draft/toc.md
- release/02-toc.md
- release/11-operations/00-toc.md
- release/11-operations/04-crs.md
- release/11-operations/toc.md
- release/toc.md
renames the CRS files to match the new naming for this project
rename CRS files
> rename CRS files

- draft/04-foundations/03-security-principles.md
When I read, The weakest link principle, it occurred to me that it wasn't really clear whether it talked about the characteristics of a system or giving me guidance as to what to do. I feel that principles on good security principles, should at least give some indication as to what is considered good security. I have added some pointers taken from "[Building Secure Software: How to Avoid Security Problems the Right Way](https://www.amazon.com/Building-Secure-Software-Security-Documents-ebook/dp/B003CW67YQ/ref=sr_1_1?crid=UV4FKMAKB5EV&dib=eyJ2IjoiMSJ9.Vkfz6-jqiSz4swfILu_CaA.qoW8VG8f8AjovY0S2eNKRi-8mpmm_4V9j6o0hH3KLZI&dib_tag=se&keywords=Building+Secure+Software%3A+How+to+Avoid+Security+Problems+the+Right+Way&qid=1723450640&s=digital-text&sprefix=building+secure+software+how+ …
> Security principles

- .github/workflows/release.yaml
- README.md
- contributing.md
- draft/04-foundations/01-security-fundamentals.md
- draft/10-culture-process/03-samm.md
- draft/13-security-gap-analysis/01-guides/01-samm.md
adds pre-release candidate to release workflow
add pre-release candidate to release workflow
> add pre-release candidate to release workflow

- README.md
- info.md
DevGuide has been promoted to OWASP Lab project status
promoted to lab project
> promotion to lab project

- .wordlist.txt
- draft/04-foundations/03-security-principles.md
- draft/05-requirements/00-toc.md
- draft/05-requirements/01-requirements.md
- draft/05-requirements/toc.md
- draft/06-design/02-web-app-checklist/01-define-security-requirements.md
- draft/06-design/02-web-app-checklist/02-frameworks-libraries.md
- draft/06-design/02-web-app-checklist/03-secure-database-access.md
- draft/06-design/02-web-app-checklist/04-encode-escape-data.md
- draft/06-design/02-web-app-checklist/05-validate-inputs.md
- draft/06-design/02-web-app-checklist/06-digital-identity.md
- draft/06-design/02-web-app-checklist/07-access-controls.md
- draft/06-design/02-web-app-checklist/08-protect-data.md
- draft/06-design/02-web-app-checklist/09-logging-monitoring.md
- draft/06-design/02-web-app-checklist/10-handle-errors-exceptions.md
- draft/07-implementation/01-documentation/01-proactive-controls.md
Update links to the new OWASP Top 10 Proactive Controls
Update links to the new OWASP Top 10 Proactive Controls. This would be important as google actually provides the developer guide as first hit when searching for "owasp proactive controls" (:
I am one of the OWASP Top 10 co-leaders.
closes #272 'Update links to the new OWASP Top 10 Proactive Controls'
> Update to new OWASP Top 10 Proactive Controls

- draft/04-foundations/00-toc.md
- draft/04-foundations/02-secure-development.md
- draft/04-foundations/toc.md
- draft/06-design/01-threat-modeling/01-threat-modeling.md
- draft/08-verification/00-toc.md
- draft/08-verification/04-vulnerability-management/01-defectdojo.md
- draft/08-verification/toc.md
- draft/09-training-education/00-toc.md
- draft/09-training-education/06-mobile-top-ten.md
- draft/09-training-education/toc.md
- draft/10-culture-process/01-security-culture.md
- draft/10-culture-process/02-security-champions/01-security-champions-program.md
- draft/12-metrics/00-toc.md
- draft/12-metrics/toc.md
- release-process.md
This adds more references to the Security Culture project in various sections throughout the DevGuide
add more references to the Security Culture project
Closes #289
> add more references to the Security Culture project

- .wordlist.txt
- _data/draft.yaml
- _data/release.yaml
- draft/02-toc.md
- draft/05-requirements/06-mas.md
- draft/06-design/03-mas-checklist.md
- draft/07-implementation/00-toc.md
- draft/07-implementation/04-maswe.md
- draft/07-implementation/toc.md
- draft/09-training-education/01-vulnerable-apps/02-webgoat.md
- draft/13-security-gap-analysis/01-guides/03-mas.md
- draft/toc.md
adds content for the MAS weakness enumeration (MASWE)
add page for MASWE
closes #246
> add page for MASWE

- _data/draft.yaml
- _data/release.yaml
- draft/07-implementation/04-maswe.md
adds content for the MAS weakness enumeration (MASWE)
add page content for MASWE
closes #246
> provide contents for MASWE page

- _data/release-pt-br.yaml
Provide the DevGuide translation to Brazilian Portuguese (this is one of https://github.com/OWASP/www-project-developer-guide/issues/267 's subtasks).
[_data/release-pt-br.yaml](https://github.com/OWASP/www-project-developer-guide/blob/main/_data/release-pt-br.yaml).
This PR resolves https://github.com/OWASP/www-project-developer-guide/issues/325.
> Translate sidebar to Brazilian Portuguese

- release-pt-br/03-introduction.md
Provide the DevGuide translation to Brazilian Portuguese (this is one of https://github.com/OWASP/www-project-developer-guide/issues/267 's subtasks).
Description for the changelog :
[release-pt-br/03-introduction.md](https://github.com/OWASP/www-project-developer-guide/blob/release-pt-br/03-introduction.md).
> Translate 03-introduction to Brazilian Portuguese

- _data/release-ja.yaml
- release-ja/01-front.md
- release-ja/02-toc.md
- release-ja/toc.md
This provides the initial file set for the Japanese translation from @silverskyvicto repo
Initial Japanese translation
This is just the start of the translation, most of the pages are yet to be translated
> Create initial Japanese translation

- release-es/04-foundations/00-toc.md
- release-es/04-foundations/01-security-fundamentals.md
- release-es/04-foundations/02-secure-development.md
- release-es/04-foundations/03-security-principles.md
- release-es/04-foundations/04-crypto-principles.md
- release-es/04-foundations/05-top-ten.md
- release-es/04-foundations/toc.md
- release-es/05-requirements/00-toc.md
- release-es/05-requirements/01-requirements.md
- release-es/05-requirements/02-risk.md
- release-es/05-requirements/03-opencre.md
- release-es/05-requirements/04-security-rat.md
- release-es/05-requirements/05-asvs.md
- release-es/05-requirements/06-mas.md
- release-es/05-requirements/07-skf.md
- release-es/05-requirements/toc.md
translation to spanish for files in folders 04-foundations and 05-requirements to current last version 4.1.7
> Spanish translations 04-05

- .github/workflows/ci.yaml
- .github/workflows/housekeeping.yaml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- .lycheeignore
- info.md
- tab_historical.md
- tab_translations.md
reduces the scope for the link checker to avoid time outs
also changes the PDF link to the new URL
reduce the link checker scope
**Declaration**:
> reduce the link checker scope
